### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by klaw772** [Insubordinate/Insubordinate.github.io#1]
Initial Thoughts:
This is a very unique and fun concept for a portfolio site! This page successfully demonstrates the content that we have gone over in bootcamp thus far, and stretches beyond that with additional styling. The mobile and desktop responsiveness still keep the theme of the page in mind, which, considering the unique structure of the page, is a cool feat to achieve. The styling on both the home page and the about page make this site visually appealing. The code is easy to read and navigate - indentation throughout all of the files is consistent, and the code itself is concise. The CSS selectors are descriptive of the elements they select, and the helpful comments for each section of the CSS file make this intuitive to read as well.

Feedback:
Consider the accessibility of your site - for example, adding alternative text to images, determining where it might be applicable to include semantic tags, including any supplemental help text on the home page to describe what the page is presenting, and adding notes for pages that are still in development. Additionally, when linking to external sites using an anchor tag, including the full path with 'https://' can ensure that the link will redirect externally, rather than appending to the path of your site and attempting to link internally. Consider adjusting the breakpoints of your media queries, as there were some points where text overflowed over their parent containers. Finally, as you continue to build out the other pages, consider determining whether a shared stylesheet between pages would be beneficial for reusability.

Great work! :)

**Comment by Insubordinate** [comment]
Thanks for the feedback! 

I will keep these points in mind for future iterations.
